#!/usr/bin/env node
"use strict";


let doc = `
Turn plain markdown/html into interactive 3-column articles

Usage: supplescroll.js [-o outhtml] markdown|html theme
    
  - themes: light, dark, yeolde, clown, sphinx

`;


if ( process.argv.length < 3 ) {

  console.log(doc);

} 
else {

    let mod = require('../supplescroll/build.js');
    let nopt = require('nopt')
    let knownOpts = {
        "out": [String, null]
    }
    let shortHands = {
        "o": ["--out"]
    }

    let parsed = nopt(knownOpts, shortHands, process.argv, 2)
    let remain = parsed.argv.remain
    const fname = remain[0];

    let theme = 'dark';
    if ( remain.length > 1 ) {
        theme = remain[1];
    } 

    let outFname;
    if (parsed.out) {
        outFname = parsed.out
    }
    else {
        outFname = fname.replace('.md', '.html');
    }

    mod.processFile(fname, theme, outFname);

}





